// <auto-generated />
namespace FanusYazilim.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tree1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tree1));
        
        string IMigrationMetadata.Id
        {
            get { return "201810102228562_tree1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
